controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Broadcast robot's state
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Advanced Differential Drive Controller
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    publish_wheel_joint_controller_state: true
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    map_frame_id: "map"
    publish_odom: true
    use_map: true
    map_topic: "/map"
    use_stamped_vel: false
    
    left_wheel_names: ["wheel_back_left_joint", "wheel_front_left_joint"]
    right_wheel_names: ["wheel_back_right_joint", "wheel_front_right_joint"]
    wheel_separation: 0.4  
    wheel_radius: 0.07     
    publish_rate: 50.0
    command_interface: "velocity"
    state_interfaces: ["velocity", "position"]


    # Velocity limits
    linear:
      x:
        max_velocity: 2.0  # m/s
        min_velocity: -2.0 # m/s
        max_acceleration: 2.0
        min_acceleration: -2.0

    angular:
      z:
        max_velocity: 2.0  # rad/s
        min_velocity: -2.0 # rad/s
        max_acceleration: 2.0
        min_acceleration: -2.0

